<a href="https://colab.research.google.com/github/saeidsaadatigero/AI_ML_Computer-Vision/blob/main/16_Transpose_%26_Inverse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# تعریف بردار و ماتریس
x = np.array([[1], [2], [3]])  # بردار ستونی
A = np.array([[1, 2, 3], [4, 5, 6]])  # ماتریس 2x3

# ضرب ماتریس در بردار
result = A @ x
print("نتیجه ضرب ماتریس در بردار:\n", result)

# ترانهاده و معکوس
B = np.array([[2, 1], [5, 3]])
B_T = B.T
B_inv = np.linalg.inv(B)

print("ترانهاده ماتریس B:\n", B_T)
print("معکوس ماتریس B:\n", B_inv)

# بررسی اینکه B * B_inv = I
identity = B @ B_inv
print("ضرب B در معکوسش:\n", identity)


نتیجه ضرب ماتریس در بردار:
 [[14]
 [32]]
ترانهاده ماتریس B:
 [[2 5]
 [1 3]]
معکوس ماتریس B:
 [[ 3. -1.]
 [-5.  2.]]
ضرب B در معکوسش:
 [[ 1.00000000e+00  2.22044605e-16]
 [-8.88178420e-16  1.00000000e+00]]
